name: UnityTestRunnerExampleSlack

on:
  push:
  schedule:
    # evry Sat (UTC)
    - cron:  '0 0 * * 6'

jobs:
  editorTestJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.2.5f1]

    steps:
    - uses: actions/checkout@master
    - run: mkdir -p path/to/artifact

    #- run: openssl aes-256-cbc -d -in Unity_v2019.x.ulf-cipher -k ${CYPHER_KEY} >> /Unity_v2019.x.ulf
      #env:
        #CYPHER_KEY: ${{ secrets.cypherkey }}
        
    #- run: |      
        #echo $ULF > /Unity_v2019.x.ulf
      #env:
        #ULF: ${{ secrets.ulf2019 }}
        
    - run: |      
        echo -n {$ULF} | base64 -d > /Unity_v2019.x.ulf
      env:
        ULF: ${{ secrets.ulf_base64 }}
        
        
    - run: /opt/Unity/Editor/Unity -manualLicenseFile /Unity_v2019.x.ulf -batchmode -nographics -quit || exit 0
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -runEditorTests -editorTestsResultFile path/to/artifact/results.xml || exit 0


        
    - uses: actions/upload-artifact@master
      with:
        name: test_results
        path: path/to/artifact
        
  reportResultJob:
    runs-on: ubuntu-latest
    needs: editorTestJob
    steps:
    - uses: actions/download-artifact@master
      with:
        name: test_results
        path: artifact
    
    
    - name: report result to slack
      run: |
        echo ls
        ls       
        cat artifact/results.xml

        # exit $INPUT_RESULT

        
